version: "2"
run:
  timeout: 10m

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - unused
    - staticcheck
    - dogsled
    - gosec
    - misspell
    - nakedret
    - unconvert
    - unparam
    - whitespace
