version: '3'

tasks:

  mmdb:
    run: once
    status:
      - test -f ./Country.mmdb
    cmds:
      - wget https://github.com/Hackl0us/GeoIP2-CN/raw/release/Country.mmdb

  xdb:
    run: once
    status:
      - test -f ./ip2region_v4.xdb
      - test -f ./ip2region_v6.xdb
    cmds:
      - wget https://github.com/lionsoul2014/ip2region/raw/master/data/ip2region_v4.xdb
      - wget https://github.com/lionsoul2014/ip2region/raw/master/data/ip2region_v6.xdb


  gofmt:
    cmds:
      - command -v goimports || go install golang.org/x/tools/cmd/goimports@latest
      - gofmt -s -w .
      - goimports -w .

  govulncheck:
    desc: vulnerability detection
    cmds:
      - command -v govulncheck || go install golang.org/x/vuln/cmd/govulncheck@latest
      - govulncheck ./...

  golint:
    cmds:
      - command -v golangci-lint || go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.57.2
      - golangci-lint run -v ./...

  gci:
    cmds:
      - command -v gci || go install github.com/daixiang0/gci@v0.13.1
      - gci write --skip-generated --custom-order -s standard -s "prefix(github.com/ysicing/caddy2-geocn)" -s default -s blank -s dot .

  fmt:
    desc: format code
    run: once
    cmds:
      - task: gofmt
      - task: gci
      - task: govulncheck

  build:
    deps:
      - mmdb
      - xdb
    cmds:
      - go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - xcaddy build
          --with github.com/ysicing/caddy2-geocn=../caddy2-geocn
          --with github.com/caddy-dns/cloudflare
          --with github.com/caddy-dns/tencentcloud
          --with github.com/caddy-dns/alidns
      - ./caddy list-modules

  run:
    cmds:
      - task: build
      - ./caddy run --config ./Caddyfile.local --adapter caddyfile

  default:
    cmds:
      - rm -rf ./caddy ./Country.mmdb ./ip2region_v4.xdb ./ip2region_v6.xdb
      - task: build
