# https://taskfile.dev

version: '3'

tasks:

  mmdb:
    run: once
    status:
      - test -f ./Country.mmdb
    cmds:
      - wget https://github.com/Hackl0us/GeoIP2-CN/raw/release/Country.mmdb

  build:
    deps:
      - mmdb
    cmds:
      - go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - xcaddy build
          --with github.com/ysicing/caddy2-geocn=../caddy2-geocn
          --with github.com/caddy-dns/cloudflare
          --with github.com/caddy-dns/tencentcloud
          --with github.com/caddy-dns/alidns
      - ./caddy list-modules

  run:
    cmds:
      - task: build
      - ./caddy run --config ./Caddyfile.local --adapter caddyfile


  default:
    cmds:
      - rm -rf ./Country.mmdb ./caddy
      - task: build
