name: Build Docker Image
on:
  push:
  # schedule:
  #   - cron: '0 */12 * * *'
jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCRIO }}
    - name: build bin
      run: |
        docker build -t ghcr.io/ysicing/caddy2-geocn .
        docker push ghcr.io/ysicing/caddy2-geocn
