name: Build Docker Image
on:
  push:
  # schedule:
  #   - cron: '0 */12 * * *'
jobs:
  build:
    name: build sdk docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Install Go
      uses: actions/setup-go@v3.2.1
      with:
        go-version: 1.17.x
    - name: install xcaddy
      run: |
          echo "install xcaddy"
          go get -u github.com/caddyserver/xcaddy/cmd/xcaddy@latest
    - name: Login GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCRIO }}
    - name: build bin
      run: |
        export TZ='Asia/Shanghai'
        export PATH=$PATH:$(go env GOPATH)/bin
        xcaddy build --with github.com/ysicing/caddy2-geocn
        rm -rf Country.mmdb
        wget https://github.com/Hackl0us/GeoIP2-CN/raw/release/Country.mmdb
        docker build -t ghcr.io/ysicing/caddy2-geocn -f example/Dockerfile .
        docker push ghcr.io/ysicing/caddy2-geocn
